import type { District, Office, UserProfile, Vehicle, Trip, AppSettings, RouteSubscription, AppNotification } from '../types';

export const INITIAL_DISTRICTS: District[] = [
  { id: 'dist_troieshchyna', name: 'Троєщина', cityPart: 'Лівий берег', popularPickupSpots: ['ТРЦ Район', 'вул. Закревського', 'м. Чернігівська', 'просп. Червоної Калини'] },
  { id: 'dist_obolon', name: 'Оболонь', cityPart: 'Правий берег', popularPickupSpots: ['м. Мінська', 'м. Оболонь', 'ТРЦ Dream Yellow', 'Оболонська Набережна'] },
  { id: 'dist_pozniaky', name: 'Позняки', cityPart: 'Лівий берег', popularPickupSpots: ['м. Позняки', 'ТРЦ Piramida', 'вул. Драгоманова', 'вул. Анна Ахматової'] },
  { id: 'dist_osokorky', name: 'Осокорки', cityPart: 'Лівий берег', popularPickupSpots: ['м. Осокорки', 'ТЦ River Mall', 'вул. Дніпровська набережна'] },
  { id: 'dist_vynohradar', name: 'Виноградар', cityPart: 'Правий берег', popularPickupSpots: ['ТРЦ Retroville', 'просп. Правди', 'просп. Свободи'] },
  { id: 'dist_borshchahivka', name: 'Борщагівка', cityPart: 'Правий берег', popularPickupSpots: ['ТРЦ Квадрат', 'вул. Гната Юри', 'м. Святошин'] },
  { id: 'dist_sofiivska', name: 'Софіївська Борщагівка', cityPart: 'Передмістя', popularPickupSpots: ['ЖК Софія', 'ЖК Щасливий', 'вул. Соборна'] },
  { id: 'dist_vyshneve', name: 'Вишневе', cityPart: 'Передмістя', popularPickupSpots: ['Залізничний вокзал Вишневе', 'вул. Європейська', 'ЖК Акварелі'] },
  { id: 'dist_kryukivshchyna', name: 'Крюківщина', cityPart: 'Передмістя', popularPickupSpots: ['ЖК Євромісто', 'вул. Бакинська'] },
  { id: 'dist_irpin', name: 'Ірпінь', cityPart: 'Передмістя', popularPickupSpots: ['Центральний парк', 'м. Академмістечко (зупинка)', 'ЖК Синергія'] },
  { id: 'dist_bucha', name: 'Буча', cityPart: 'Передмістя', popularPickupSpots: ['Новус Буча', 'Центральний сквер'] },
  { id: 'dist_brovary', name: 'Бровари', cityPart: 'Передмістя', popularPickupSpots: ['ТРЦ Термінал', 'м. Лісова (посадка)', 'вул. Незалежності'] },
  { id: 'dist_akadem', name: 'Академмістечко', cityPart: 'Правий берег', popularPickupSpots: ['м. Академмістечко', 'просп. Палладіна'] },
  { id: 'dist_teremky', name: 'Теремки', cityPart: 'Правий берег', popularPickupSpots: ['м. Теремки', 'м. Іподром', 'ТРЦ Республіка Park'] },
  { id: 'dist_solomianka', name: 'Солом\'янка', cityPart: 'Правий берег', popularPickupSpots: ['Солом\'янська площа', 'Севастопольська площа', 'м. Вокзальна'] },
];

export const INITIAL_OFFICES: Office[] = [
  { id: 'off_zhylianska', name: 'ГО ОТПБанк (Головний офіс)', address: 'м. Київ, вул. Жилянська, 43', districtId: 'dist_solomianka', isMainHQ: true },
  { id: 'off_fizkultury', name: 'Офіс OTP (вул. Фізкультури)', address: 'м. Київ, вул. Фізкультури, 30', districtId: 'dist_solomianka', isMainHQ: false },
  { id: 'off_vasylkivska', name: 'Центральне відділення OTP', address: 'м. Київ, вул. Велика Васильківська, 5', districtId: 'dist_solomianka', isMainHQ: false },
];

export const INITIAL_USER: UserProfile = {
  id: 'usr_me',
  name: 'Олександр',
  surname: 'Коваленко',
  email: 'oleksandr.kovalenko@otpbank.com.ua',
  phone: '+380 67 123 4567',
  telegramUsername: 'alex_kovalenko_otp',
  department: 'IT Департамент',
  districtId: 'dist_troieshchyna',
  officeId: 'off_zhylianska',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  isConfirmed: true,
  completedTripsCount: 14,
  cancelledTripsCount: 0,
  noShowCount: 0,
  preferredRoleMode: 'passenger',
  isAdmin: true,
};

export const INITIAL_VEHICLES: Vehicle[] = [
  { id: 'veh_1', ownerId: 'usr_me', make: 'Skoda', model: 'Octavia A7', color: 'Сірий металік', plateNumber: 'KA 7788 CB', seats: 4, comment: 'Чистий салон, кондиціонер, хороша музика', isDefault: true },
  { id: 'veh_2', ownerId: 'usr_me', make: 'Volkswagen', model: 'Golf 7', color: 'Чорний', plateNumber: 'AA 1122 OP', seats: 3, isDefault: false },
];

export const INITIAL_SETTINGS: AppSettings = {
  appName: 'OTP Попутник',
  companyName: 'ОТП Банк',
  allowedDomains: ['otpbank.com.ua', 'otp.ua'],
  mainOfficeAddress: 'м. Київ, вул. Жилянська, 43',
  supportTelegram: 'otp_carpool_support',
  autoApproveRequestsDefault: false,
};

const TODAY_DATE = new Date().toISOString().split('T')[0];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip_1',
    driverId: 'usr_andrii',
    driverName: 'Андрій Мельник',
    driverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    driverDepartment: 'Департамент ризиків',
    driverTelegram: 'andrii_melnyk_otp',
    driverPhone: '+380 50 987 6543',
    vehicleId: 'veh_andrii',
    vehicleInfo: 'Skoda Octavia A7 (Сірий)',
    vehiclePlate: 'KA 7788 CB',
    tripType: 'to_office',
    originDistrictId: 'dist_troieshchyna',
    originDistrictName: 'Троєщина',
    originSpot: 'ТРЦ Район (зупинка біля Сильпо)',
    destinationOfficeId: 'off_zhylianska',
    destinationOfficeName: 'ГО ОТПБанк',
    destinationAddress: 'вул. Жилянська, 43',
    departureDate: TODAY_DATE,
    departureTime: '07:45',
    recurrence: { type: 'every_other_day', label: 'Через день (робочі дні)' },
    availableSeats: 3,
    initialSeats: 4,
    approvalMode: 'manual',
    compensationType: 'fixed_contribution',
    compensationAmount: 60,
    compensationNotes: 'Скидаємося по 60 грн на бензин',
    maxWaitMinutes: 5,
    luggageAllowed: true,
    childSeatAvailable: false,
    petsAllowed: false,
    comment: 'Їду через Північний міст та Набережно-Хрещатицьку до Жилянської 43. Можу забрати по дорозі на Почайні чи Поштової.',
    status: 'PUBLISHED',
    stops: [
      { id: 's1', name: 'ТРЦ Район (Троєщина)', estimatedTime: '07:45', order: 1 },
      { id: 's2', name: 'м. Почайна (зупинка)', estimatedTime: '08:05', order: 2 },
      { id: 's3', name: 'ГО ОТПБанк (Жилянська 43)', estimatedTime: '08:30', order: 3 },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'trip_2',
    driverId: 'usr_olena',
    driverName: 'Олена Шевченко',
    driverAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    driverDepartment: 'Операційний департамент',
    driverTelegram: 'olena_shevchenko_otp',
    driverPhone: '+380 63 333 4455',
    vehicleId: 'veh_olena',
    vehicleInfo: 'Volkswagen Passat B8 (Темно-синій)',
    vehiclePlate: 'AA 4411 BB',
    tripType: 'to_office',
    originDistrictId: 'dist_pozniaky',
    originDistrictName: 'Позняки',
    originSpot: 'м. Позняки (біля ТРЦ Піраміда)',
    destinationOfficeId: 'off_zhylianska',
    destinationOfficeName: 'ГО ОТПБанк',
    destinationAddress: 'вул. Жилянська, 43',
    departureDate: TODAY_DATE,
    departureTime: '08:00',
    recurrence: { type: 'workdays', label: 'Щодня у робочі дні' },
    availableSeats: 2,
    initialSeats: 3,
    approvalMode: 'auto',
    compensationType: 'free',
    compensationNotes: 'Підвезти колег безкоштовно, радий компанії!',
    maxWaitMinutes: 5,
    luggageAllowed: false,
    childSeatAvailable: true,
    petsAllowed: false,
    comment: 'Їду через міст Патона на Жилянську. Теплий салон, приємне радіо.',
    status: 'PUBLISHED',
    stops: [
      { id: 's1', name: 'м. Позняки', estimatedTime: '08:00', order: 1 },
      { id: 's2', name: 'м. Осокорки', estimatedTime: '08:07', order: 2 },
      { id: 's3', name: 'ГО ОТПБанк (Жилянська 43)', estimatedTime: '08:40', order: 3 },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'trip_3',
    driverId: 'usr_sergiy',
    driverName: 'Сергій Петренко',
    driverAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    driverDepartment: 'Юридичний департамент',
    driverTelegram: 'sergiy_law_otp',
    driverPhone: '+380 67 999 1122',
    vehicleId: 'veh_sergiy',
    vehicleInfo: 'Toyota RAV4 (Білий)',
    vehiclePlate: 'AI 0099 OO',
    tripType: 'to_office',
    originDistrictId: 'dist_irpin',
    originDistrictName: 'Ірпінь',
    originSpot: 'Центральний парк Ірпеня (біля кафе)',
    destinationOfficeId: 'off_zhylianska',
    destinationOfficeName: 'ГО ОТПБанк',
    destinationAddress: 'вул. Жилянська, 43',
    departureDate: TODAY_DATE,
    departureTime: '07:30',
    recurrence: { type: 'every_other_day', label: 'Через день' },
    availableSeats: 3,
    initialSeats: 4,
    approvalMode: 'manual',
    compensationType: 'fixed_contribution',
    compensationAmount: 70,
    compensationNotes: 'по 70 грн на пальне',
    maxWaitMinutes: 10,
    luggageAllowed: true,
    childSeatAvailable: true,
    petsAllowed: true,
    comment: 'Виїжджаю з Ірпеня через Романівку та Академмістечко на Жилянську 43.',
    status: 'PUBLISHED',
    stops: [
      { id: 's1', name: 'Ірпінь (Центральний парк)', estimatedTime: '07:30', order: 1 },
      { id: 's2', name: 'м. Академмістечко', estimatedTime: '07:55', order: 2 },
      { id: 's3', name: 'ГО ОТПБанк (Жилянська 43)', estimatedTime: '08:35', order: 3 },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'trip_4_evening',
    driverId: 'usr_andrii',
    driverName: 'Андрій Мельник',
    driverAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    driverDepartment: 'Департамент ризиків',
    driverTelegram: 'andrii_melnyk_otp',
    driverPhone: '+380 50 987 6543',
    vehicleId: 'veh_andrii',
    vehicleInfo: 'Skoda Octavia A7 (Сірий)',
    vehiclePlate: 'KA 7788 CB',
    tripType: 'from_office',
    originDistrictId: 'dist_solomianka',
    originDistrictName: 'ГО ОТПБанк (Жилянська 43)',
    originSpot: 'Парковка біля головного входу ГО Жилянська 43',
    destinationOfficeId: 'dist_troieshchyna',
    destinationOfficeName: 'Троєщина (ТРЦ Район)',
    destinationAddress: 'просп. Червоної Калини / ТРЦ Район',
    departureDate: TODAY_DATE,
    departureTime: '18:15',
    recurrence: { type: 'every_other_day', label: 'Через день (робочі дні)' },
    availableSeats: 3,
    initialSeats: 4,
    approvalMode: 'manual',
    compensationType: 'fixed_contribution',
    compensationAmount: 60,
    compensationNotes: 'по 60 грн у зворотному напрямку',
    maxWaitMinutes: 10,
    luggageAllowed: true,
    childSeatAvailable: false,
    petsAllowed: false,
    comment: 'Назад з робочого місця на Жилянській 43 на Троєщину після завершення дня.',
    status: 'PUBLISHED',
    stops: [
      { id: 's1', name: 'ГО ОТПБанк (Жилянська 43)', estimatedTime: '18:15', order: 1 },
      { id: 's2', name: 'м. Почайна', estimatedTime: '18:40', order: 2 },
      { id: 's3', name: 'Троєщина (ТРЦ Район)', estimatedTime: '19:00', order: 3 },
    ],
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_SUBSCRIPTIONS: RouteSubscription[] = [
  {
    id: 'sub_1',
    userId: 'usr_me',
    districtId: 'dist_troieshchyna',
    districtName: 'Троєщина',
    destinationOfficeId: 'off_zhylianska',
    destinationOfficeName: 'ГО ОТПБанк (Жилянська 43)',
    tripType: 'to_office',
    departureTimeRange: '07:30 - 08:30',
    isActive: true,
  }
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif_1',
    userId: 'usr_me',
    title: '🚗 Поїздка знайдена!',
    message: 'Колега Андрій Мельник (Троєщина -> ГО Жилянська 43) опублікував поїздку "Через день" на 07:45.',
    type: 'subscription_match',
    tripId: 'trip_1',
    isRead: false,
    createdAt: new Date().toISOString(),
  }
];
